redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\mhmd\\Desktop\\projects\\testvite\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\mhmd\\Desktop\\projects\\testvite\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "vite build"
functions = "C:\\Users\\mhmd\\Desktop\\projects\\testvite\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]